services:
  ns3:
    image: ghcr.io/nico-ig/p4sim-ns3
    container_name: ns3-p4sim
    tty: true
    volumes:
      - ../ns3-scripts/:/home/p4user/workdir/ns3.39/scratch
      - ../ns3-logs/:/home/p4user/workdir/ns3.39/logs
